name: Apodidonai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63506
title: 'Give back!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#13110c'
    - '#986f78'
    - '#ff0059'
    - '#33c060'
  brandStrength: 0.5977059479337186
  lightness: 0.9375
  saturation: 0.4343328147660941
  rhythmicContrast: 0.25
purpose: []
