name: Apodidonai
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63506
title: 'Apodidonai - Give back!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#13110c'
    - '#986f78'
    - '#ff0059'
    - '#33c060'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
